version: '3.1'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    networks:
      webnet:
        ipv4_address: 10.5.0.2

  node_1:
    image: sybline
    hostname: node_1
    mem_limit: 1000m
    env_file:
      - sybline_one.env
    volumes:
      - './node_1_data:/node_data'
      - './cert:/cert'
    ports:
      - 2221:2221
      - 8080:8080
    networks:
      webnet:
        ipv4_address: 10.5.0.4

  node_2:
    image: sybline
    hostname: node_2
    mem_limit: 1000m
    env_file:
      - sybline_two.env
    volumes:
      - './node_2_data:/node_data'
      - './cert:/cert'
    ports:
      - 2222:2221
      - 8081:8080
    networks:
      webnet:
        ipv4_address: 10.5.0.5

  node_3:
    image: sybline
    hostname: node_3
    mem_limit: 1000m
    env_file:
      - sybline_three.env
    volumes:
      - './node_3_data:/node_data'
      - './cert:/cert'
    ports:
      - 2223:2221
      - 8082:8080
    networks:
      webnet:
        ipv4_address: 10.5.0.6

networks:
  webnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
