version: '3.1'

services:
  node_1:
    image: greedykomodo/sybline:latest
    hostname: node_1
    mem_limit: 1000m
    environment:
      - SERVER_PORT=2221
      - RAFT_NODE_ID=node1
      - RAFT_PORT=1111
      - RAFT_VOL_DIR=node_data
      - TLS_ENABLED=false
      - NODES=node2,node3
      - ADDRESSES=node_2:1111,node_3:1111
      - BATCH_LIMIT=10000
      - SNAPSHOT_THRESHOLD=20000
      - SNAPSHOT_RETENTION_COUNT=3
      - CACHE_LIMIT=500
      - HOST_IP=node_1
      - TOKEN_DURATION=1800
      - SALT=salty
    volumes:
      - './node_1_data:/app/node_data'
      - './cert:/cert'
    ports:
      - 2221:2221
      - 7878:7878
    networks:
      webnet:
        ipv4_address: 10.5.0.4

  node_2:
    image: greedykomodo/sybline:latest
    hostname: node_2
    mem_limit: 1000m
    environment:
      - SERVER_PORT=2221
      - RAFT_NODE_ID=node2
      - RAFT_PORT=1111
      - RAFT_VOL_DIR=node_data
      - TLS_ENABLED=false
      - NODES=node1,node3
      - ADDRESSES=node_1:1111,node_3:1111
      - BATCH_LIMIT=10000
      - SNAPSHOT_THRESHOLD=20000
      - SNAPSHOT_RETENTION_COUNT=3
      - CACHE_LIMIT=500
      - HOST_IP=node_2
      - TOKEN_DURATION=1800
      - SALT=salty
    volumes:
      - './node_2_data:/node_data'
      - './cert:/cert'
    ports:
      - 2222:2221
      - 7879:7878
    networks:
      webnet:
        ipv4_address: 10.5.0.5

  node_3:
    image: greedykomodo/sybline:latest
    hostname: node_3
    mem_limit: 1000m
    environment:
      - SERVER_PORT=2221
      - RAFT_NODE_ID=node3
      - RAFT_PORT=1111
      - RAFT_VOL_DIR=node_data
      - TLS_ENABLED=false
      - NODES=node1,node2
      - ADDRESSES=node_1:1111,node_2:1111
      - BATCH_LIMIT=10000
      - SNAPSHOT_THRESHOLD=20000
      - SNAPSHOT_RETENTION_COUNT=3
      - CACHE_LIMIT=500
      - HOST_IP=node_3
      - TOKEN_DURATION=1800
      - SALT=salty
    volumes:
      - './node_3_data:/node_data'
      - './cert:/cert'
    ports:
      - 2223:2221
      - 7880:7878
    networks:
      webnet:
        ipv4_address: 10.5.0.6

networks:
  webnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
