global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sybline'
    static_configs:
      - targets: ['node_1:8080', 'node_2:8080', 'node_3:8080']
