name: Github CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Go Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      - run: go test -v ./pkg/...

  trivy-alpine:
    name: trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: |
          docker build -t sybline:${{ github.sha }} -f infra/docker/sybline.dockerfile .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'sybline:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  trivy-ubi:
    name: trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: |
          docker build -t sybline-ubi:${{ github.sha }} -f infra/docker/UBI.dockerfile .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'sybline-ubi:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
